# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/infinix/Infinix-X6816/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),Infinix-X6816)

endif
